### PR TITLE
Update Python versions

### PR DESCRIPTION
**Pull request by terencehonles**
This change adds all missing Python versions starting at Python 2.7.13.

This can be performed by following these steps:

1. Go to https://www.python.org/downloads/
2. Scrape the downloads with:

   ```javascript
   JSON.stringify(Array.from(
     document.querySelectorAll('.download-list-widget .release-number a'),
     (i) => i.innerText.replace(/Python\s+/, '')))
    ```

3. Clean up with Python:

   ```python
   versions = sorted(
      tuple(int(j) for j in i.split('.')) for i in PARSED_JSON_VERSIONS)
   ```

4. Filter and print (use '\n' or ' ' as the separator as needed)

   ```python
   print(' '.join(
     '.'.join(str(j) for j in v) for v in versions if v >= (2, 7, 13)))
   ```

### CODE REVIEW

**Comment by randomknowledge** [comment]
Hi @terencehonles,
actually I would not want to remove python versions, not even patch releases, because this image is used for testing exact versions. Could you add the new releases without removing the old ones?

**Comment by terencehonles** [comment]
@randomknowledge yeah I'm fine with that, did you want me to add all patch versions? there's quite a few missing. I went with removing rather than adding all since I didn't want to bloat the image too much.

**Comment by terencehonles** [comment]
I'm not sure how this is being build but it also seems like this might be more appropriately passed in as a build arg. That way the env could use it with `ENV PYTHON_VERSIONS=${PYTHON_VERSIONS}` and the file could be created with `tr ' ' '\n' <<<${PYTHON_VERSIONS} > versions-file-in-container`

All of this is assuming the `--build-arg PYTHON_VERSIONS=` is set to what is currently set in the Dockerfile `ENV` command.

**Comment by terencehonles** [comment]
I could probably create a github workflow that runs on a cron job and add it to this repo if you'd like. You'd need to set up the secrets so that it could actually push to docker hub, but I could at least outline the build modifications.

**Comment by randomknowledge** [comment]
@terencehonles 
Thanks for the effort! I am personally not interested in adding _all_ patch versions. But I do not want existing ones to be removed, in cased they are still used.
I like the Idea of using a build arg with a Github workflow. Feel free to make a pull request.

**Comment by randomknowledge** [comment]
@terencehonles 
Please also have a look at https://github.com/randomknowledge/docker-pyenv-tox/pull/6
This PR updates ubuntu and node and removes python2 (from the image, not the pyenv version) and fabric.

**Pull request merged**
